### ISSUE TITLE
백엔드 연결 전 진행하는 자체 QA

### ISSUE THREAD

**Issue by karpitony** [team1-booklog/Frontend#29]
## 노션 참고
https://www.notion.so/stern015/QA-95cddd2bda2449328a59e106fb8cf0c5

## 헤더
- [x] 패딩 조절해서 밑이랑 좀 거리두기
- [x] 모바일에서는 로그아웃 버튼 대신 드롭다운으로

## 메인페이지
- [ ] 검색바와 하단 콘텐츠 사이 경계선 추가
- [ ] 검색 시 돋보기에서 X 아이콘으로 변경

## 에디터 페이지

- [ ] 검색 시 돋보기에서 X 아이콘으로 변경 (선택하면 다시 돋보기 아이콘으로)

## 책 상세 페이지
- [x] 독후감이 없을 경우 페이지에서 아이콘과 텍스트 사이 간격 조정
- [x] 로그인 하지 않은 경우 페이지 추가

## 로그인 페이지
- [x] 로그인 완료 후 메인 페이지가 아닌, 이전 페이지로 라우팅
- [x] 비밀번호 input type 변경
- [ ] 모바일 디자인 적용

## 회원가입 페이지
- [ ] 모바일 디자인 적용

**Comment by gmlwlsdl** [comment]
혹시 저도 여기 이슈에 참여해도 될까요? 아님 따로 파는 게 나을까요

**Comment by karpitony** [comment]
@gmlwlsdl 편하게 쓰셔도 됩니다! 모두 작성하고 공유하는 목록 느낌으로 만드려 했거든요!
각 페이지 별로 항목을 나눠서 써주시면 될 거 같아요
